### ISSUE TITLE
Apple's issues: Data for May 11-12 is not available

### ISSUE THREAD

**Issue by ActiveConclusion** [ActiveConclusion/COVID19_mobility#11]
As I [predicted](https://github.com/ActiveConclusion/COVID19_mobility/issues/6#issuecomment-628123792), today there are problems with updates on the Apple website. As reported on their [website](https://www.apple.com/covid19/mobility):

> Data for May 11-12 is not available and will appear as blank columns in the data set.

In this repository, the [raw report](https://github.com/ActiveConclusion/COVID19_mobility/blob/master/apple_reports/applemobilitytrends.csv) will be the same as on the site, but the [preprocessed report](https://github.com/ActiveConclusion/COVID19_mobility/blob/master/apple_reports/apple_mobility_report.csv) will not be affected in any way. 
I will monitor the situation in the future and hope that Apple will fix the issues as soon as possible.

**Comment by Banistas** [comment]
Hi. Due to those issues, it look like the raw csv file is missing data for the 11th and 12th of May, even though this data is now available on the Apple site. I thought I'd let you know, so you could potentially look into refreshing the data to include those numbers. Cheers.

**Comment by ActiveConclusion** [comment]
Hi! I just checked again and see that Apple added data for May 13, but data for May 11-12 remain blank (such as in this repository). My script automatically processes the original CSV file from the [Apple site](https://www.apple.com/covid19/mobility).

**Comment by ActiveConclusion** [comment]
Apple has already added data for the week after May 12, but data for May 11-12 is still missing. Unfortunately, it looks like this data won't be available permanently... It's very sad, given the fact that it is for these dates data is particularly interesting that in many countries quarantine restrictions weakened.
Added note about this issue in README.
