### ISSUE TITLE
How correctly to cite your dataset for publication?

### ISSUE THREAD

**Issue by annabonner** [ActiveConclusion/COVID19_mobility#25]
First of all, thank you for providing this data!
I am using your dataset in my research (merged Google and Apple data: https://github.com/ActiveConclusion/COVID19_mobility/blob/master/summary_reports/summary_report_regions.csv), but I don't know how correctly write a reference for it. I don't understand, what does it mean "ActiveConclusion"? Is it some organisation or a simple nickname? Could you elaborate, please, how is better to cite your dataset for publication?
Thank you very much!

**Comment by ActiveConclusion** [comment]
To be honest, I don't know how it is academically legal to cite this repository, as it is just an aggregator of other data sources. I think the most important is to cite the original data sources. For example, Google [here](https://www.google.com/covid19/mobility/data_documentation.html?hl=en) asks you to do it like this:
Google LLC "Google COVID-19 Community Mobility Reports".
https://www.google.com/covid19/mobility/ Accessed: <date>.

But if you very want to cite my repository in your research, I suggest you do it something like this:
Kulik O. (2020). COVID-19 Mobility Data Aggregator. Online: https://github.com/ActiveConclusion/COVID19_mobility Accessed: <date>

ActiveConclusion it's just nickname. I have created a separate account for this data for some reasons. Real me, for example, in Linkedin here: https://www.linkedin.com/in/oleh-kulik/

**Comment by annabonner** [comment]
@ActiveConclusion Thank you, I appreciate it! I think that data aggregation it's not an easy problem, so it would be unfair not to cite your repository in my research.
I researched more deeply the question of citing the Github repository in an academic paper and found this [guide](https://guides.github.com/activities/citable-code/). It would be great if you made these instructions for your repository. Please, check this guide if you can.
Thank you very much!

**Comment by ActiveConclusion** [comment]
@annabonner Ok, I'll try to implement it in this repository. Thank you for the good suggestion!

**Comment by ActiveConclusion** [comment]
I added my repository to Zenodo. It's available here: https://zenodo.org/record/3978281#.XzFXaij7RPY. But, unfortunately, I was not able to make this repository automatically synchronize with Zenodo on every update. I will probably update the data there regularly manually (weekly or monthly).

So, now you can cite this source like this:
Kulik O. (2020). COVID-19 Mobility Data Aggregator. Online: http://doi.org/10.5281/zenodo.3977029
This DOI represents all versions, and will always resolve to the latest one. But you can choose specific DOI for a specific version.

**Comment by annabonner** [comment]
That's great! Thank you very much!
