### ISSUE TITLE
Tomtom data

### ISSUE THREAD

**Issue by ibarraespinosa** [ActiveConclusion/COVID19_mobility#28]
Hello friends, thank you for this repo. Do you have any plans to include tomtom traffic index? https://www.tomtom.com/en_gb/traffic-index/

**Comment by ActiveConclusion** [comment]
Hello @ibarraespinosa! Thank you for a good idea, I think it would be great to add this data to this repository. I will try to do it in my spare time.

**Comment by ActiveConclusion** [comment]
@ibarraespinosa I added TomTom data, you can get it [here](https://github.com/ActiveConclusion/COVID19_mobility#tomtom-reports).
