### ISSUE TITLE
if filename not in files_source: --> to generate report

### ISSUE THREAD

**Issue by giorgiomondauto** [ActiveConclusion/COVID19_mobility#3]
In order to generate the report, it should not be:
'if filename in files_source' instead of 'if filename not in files_source':

**Comment by ActiveConclusion** [comment]
If you want to generate the reports from scratch, delete next files:
1. "report_source.txt" - it's a file with PDFs list on which current reports are created and based on this file there is a check for adding new data.
2. Folder 'data'. Or if you don't want to download all PDFs from Google website again, set variable "new_files_status" to True in function "run".
3. The current generated reports or change destination arguments in function "run".

I understand that in my repository is lack of explanations of some features, but I will try to correct this issue as possible. If something else is unclear, feel free to ask any questions.
Thanks!

**Comment by giorgiomondauto** [comment]
Ah no. Your repository looks great as well as your code. Thanks for sharing it ;).

**Comment by ActiveConclusion** [comment]
Did you manage to run the code?

**Comment by giorgiomondauto** [comment]
Yes Thanks a lot
