### ISSUE TITLE
summary_report_countries updates

### ISSUE THREAD

**Issue by MartinHBA** [ActiveConclusion/COVID19_mobility#33]
hi team, we have last update 4 days ago, is it your automation working ok? why we don't have updates on this dataset please?

**Comment by ActiveConclusion** [comment]
Hi @MartinHBA! Thanks for reporting the issue, I will try to fix it asap.

**Comment by ActiveConclusion** [comment]
@MartinHBA The issue has been resolved. Sorry for the inconvenience.

**Comment by MartinHBA** [comment]
thanks!
