### ISSUE TITLE
missing March 12th

### ISSUE THREAD

**Issue by MartinHBA** [ActiveConclusion/COVID19_mobility#37]
Hello, I see missing data in dataset for Apple data on March 12th
dataset for Slovakia 
https://github.com/ActiveConclusion/COVID19_mobility/raw/master/summary_reports/summary_report_countries.xlsx
it's all "null" that day, but days before and after are okay

**Comment by ActiveConclusion** [comment]
Hello @MartinHBA! Unfortunately, it's a [source](https://covid19.apple.com/mobility) issue 😕
![image](https://user-images.githubusercontent.com/63144882/111373389-8049a280-86a4-11eb-925c-878756867fe2.png)

**Comment by MartinHBA** [comment]
Oh.... :(
