### ISSUE TITLE
summary report waze for europe

### ISSUE THREAD

**Issue by MartinHBA** [ActiveConclusion/COVID19_mobility#43]
hi guys, looks like Waze data stopped around 20.7.

**Comment by ActiveConclusion** [comment]
Hey @MartinHBA! Thank you for reporting. It seems that Waze has stopped updating its data.
![image](https://user-images.githubusercontent.com/63144882/129272505-168cb449-316a-4ce3-93a8-44ee7158ceeb.png)
![image](https://user-images.githubusercontent.com/63144882/129272672-d1c77f76-e77c-479c-aa5f-1f4295f3ed1b.png)

**Comment by MartinHBA** [comment]
thx a lot!
