### ISSUE TITLE
Waze Data Has Returned

### ISSUE THREAD

**Issue by hhammoud23** [ActiveConclusion/COVID19_mobility#46]
Hi,

Thank you so much for writing these scrapers and providing this data. I noticed that the Waze data stopped updating in July. Although it was paused for a time, it seems like they're now providing data again if you look at their website. Is there any way to continue updating the scraper? Thanks!

**Comment by ActiveConclusion** [comment]
Hi @hhammoud23! That's great, thank you that you spotted that! I will check the old scraper for Waze or will make a new one for it.

**Comment by ActiveConclusion** [comment]
Waze data has been updated.

**Comment by ActiveConclusion** [comment]
Waze data is updated properly.
