### ISSUE TITLE
Error in Google Reports?

### ISSUE THREAD

**Issue by ActiveConclusion** [ActiveConclusion/COVID19_mobility#5]
I've been trying to calculate total values for the US through state values. It is intuitively clear that the value of each state must be weighed with the number of the state population, so the formula for the total value has the following form:
![equation](https://latex.codecogs.com/gif.latex?Value_{i}&space;=&space;\frac{\sum_{j=1}^{Nstates}&space;value_{i}^{state_{j}}*population^{state_{j}}}{\sum&space;_&space;{j=1}^{Nstates}population^{state_{j}}})
This approach gave almost the same results as the total values in the report (difference less than 1%) except for the category "parks", and I can't give any logical explanation for this mismatch. My calculations in Google sheets [here](https://docs.google.com/spreadsheets/d/1z32FxwGXdaEpIzYCNopSNhBg_m4nYg2ZWNpDN7QpQ7o/edit?usp=sharing) (see columns M:R).
What's wrong? Where is an error? Maybe, I made a somewhere simple mistake in calculations.

**Comment by Uettwillera** [comment]
Probably tourists/visitors from abroad/another state?

**Comment by ActiveConclusion** [comment]
@Uettwillera Maybe. Or maybe in some states, people regularly go to parks, and in others, they don't usually go there, so for the second one, quarantine really doesn't affect park attendance. But according to these calculations, it looks like this difference between states is significant, and it would be interesting to know where the anomaly is.
In any case, the calculation of the total values for some set of regions using this naive approach should be interpreted with caution, and this is a clear example of why.
