### ISSUE TITLE
Waze data is not up to date

### ISSUE THREAD

**Issue by Tomkernow** [ActiveConclusion/COVID19_mobility#52]
Hi,

Waze mobility data has not been updated for 10 days. 

How can we fix this issue? 

Cheers

**Comment by Tomkernow** [comment]
Hi! 

Thanks for your quick response. 
I would love to hlep but do not have the quant skills to be of much use.... 
Do you think you will have time to fix it by the end of the week? If not, I can ask around for some help. 

Best regards

**Comment by ActiveConclusion** [comment]
Manually updated on 15.02.22

**Comment by Tomkernow** [comment]
I appreciate you taking the time to update the values! Big help! 
I hope you stay safe and well....

**Comment by oleh-kulik** [comment]
I need more time to investigate how to rework scraper. I will update data manually at the moment.

**Comment by ActiveConclusion** [comment]
Manually updated 22.02.22 (twosday)

**Comment by Tomkernow** [comment]
Thanks a lot for updating everything manually! Please continue to do so if possible...... 
Hope you are staying safe!

**Comment by ActiveConclusion** [comment]
Thank you, I am holding on and I am sure that we'll win this war. I can update the data during breaks between bombardments. But also I think it will be a good idea to provide instructions/accesses for someone else for updating the data. Volunteers are welcome.

Glory to Ukraine! Glory to Heroes!

**Comment by Tomkernow** [comment]
Hi. Hope all is okay on your side....  Can you update the data?  Instructions for the update are welcome - please post them here when possible - I can give it a go.
Cheers!

**Comment by ActiveConclusion** [comment]
Thanks, I am fine. Good, I will post instructions as soon as I can. Checked for updates, but it seems that Waze didn't update the data on their source https://datastudio.google.com/reporting/fe8a3c7d-9303-4e70-8acb-4e042714fa76/page/bhuOB

**Comment by Tomkernow** [comment]
Hi! I have contacted Waze and they have updated their data

**Comment by ActiveConclusion** [comment]
Manually updated 12.03.22

**Comment by ActiveConclusion** [comment]
Manually updated 21.03.22
P.S. Shopping mall in Kyiv before and after russian demilitarisation 😡
![Kyiv](https://user-images.githubusercontent.com/63144882/159344615-c28e7671-ac8d-4e6c-b56a-c0257b564a7e.jpg)

**Comment by Tomkernow** [comment]
Damn that's absolutely crazy....

**Comment by Tomkernow** [comment]
I don't think I have access to the repo in order to update files manually

**Comment by ActiveConclusion** [comment]
Hi @Tomkernow! I sent you an invite to the repo: https://github.com/ActiveConclusion/waze_mobility_scraper
You should accept it here:
![github-invite](https://user-images.githubusercontent.com/63144882/160402321-05d9c777-0505-402f-9a42-9911e9e060e2.png)
Please let me know if you will have any other issues.
Thank you!

**Comment by Tomkernow** [comment]
Ah... it has expired. Please send again if possible

**Comment by ActiveConclusion** [comment]
Manually updated 29.03.22

**Comment by Tomkernow** [comment]
CHEERS - please make sure is is updated again. 
If possible, please post instruction on how to write new code to automise this.

**Comment by ActiveConclusion** [comment]
Implemented a draft version of the new scraper. Testing results.

**Comment by ActiveConclusion** [comment]
Successfully updated with scraper 11.04. Closing this issue. Will reopen if needed.
