### ISSUE TITLE
WAZE Mobility DATA not updated 

### ISSUE THREAD

**Issue by VZHARO** [ActiveConclusion/COVID19_mobility#55]
Hi all, 

The WAZE Mobility data has not been updated for the past 17 days. Could you please have a look and update it if you can as I can see that there are some new data points available.

Thank you in advance,

Regards

**Comment by ActiveConclusion** [comment]
Updated 27.06

**Comment by VZHARO** [comment]
Good morning!

I hope you are doing well.

May I kindly ask you to run the scrapper for WAZE data one more time, as I
need recent pints for an update!

Thanks you in advance.

Regards,

Viktor

**Comment by ActiveConclusion** [comment]
Updated 05.07

**Comment by ActiveConclusion** [comment]
Updated 09.07

**Comment by ActiveConclusion** [comment]
No updates since 09.07

**Comment by VZHARO** [comment]
Good morning!

I hope this email finds you well.

I have noticed that there are some new points available for July, may i
kindly ask you to update the file.

I wish you a lovely day.

Regards,

VZ

**Comment by ActiveConclusion** [comment]
Updated 22.07
P.S. Most likely, this update will be the last...
<img width="463" alt="image" src="https://user-images.githubusercontent.com/63144882/180564949-4726fe7d-fd04-4d14-8424-f8e6bacda31e.png">

**Comment by ActiveConclusion** [comment]
Waze Covid-19 Impact dashboard has been retired and will no longer be updated as of July 2022. Added a note about that in Readme.
But the good news is that TomTom reports are now available again. Feel free to use them.
Closing this issue.

**Comment by VZHARO** [comment]
Good afternoon!

Thanks for the update, everything is clear now. I will have a look at Tom
Tom reports in order to see to what extend they can be used.

I wish you a lovely day.

Regards,

Viktor


Вс, 31 июля 2022 г. в 12:28, ActiveConclusion ***@***.***>:
