### ISSUE TITLE
Bring back raw Apple mobility data

### ISSUE THREAD

**Issue by lisacharlotterost** [ActiveConclusion/COVID19_mobility#9]
Thanks for providing the data! I noticed that since this morning, the raw CSV file with the Apple data [leads to a 404](https://github.com/ActiveConclusion/COVID19_mobility/blob/master/apple_reports/applemobilitytrends.csv). Would be very much appreciated if you could bring it back :) Thank you!

**Comment by ActiveConclusion** [comment]
Sorry for the inconvenience, I was making some fixes in the repository at the same time, so the file was temporarily missing( It's in place now.

**Comment by lisacharlotterost** [comment]
Great, thank you!
